"""
services/security_service.py
─────────────────────────────
Handles encryption / decryption of PII fields using Fernet
(AES-128-CBC + HMAC-SHA256).  The encryption key must be a valid
URL-safe base64-encoded 32-byte key generated by Fernet.generate_key().

Environment variable: ENCRYPTION_KEY
Generate one-time with:
    python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
"""

from __future__ import annotations

import logging
from typing import Optional

from cryptography.fernet import Fernet, InvalidToken

from config.settings import settings

logger = logging.getLogger(__name__)


class SecurityService:
    """
    Symmetric encryption wrapper for PII fields.

    • encrypt()  → bytes suitable for BLOB storage
    • decrypt()  → plaintext string (or None on failure / null input)
    """

    def __init__(self) -> None:
        if not settings.ENCRYPTION_KEY:
            raise ValueError(
                "ENCRYPTION_KEY is not set. "
                "Generate one with: python -c \"from cryptography.fernet import Fernet; "
                "print(Fernet.generate_key().decode())\""
            )
        try:
            self._fernet = Fernet(settings.ENCRYPTION_KEY.encode())
        except Exception as exc:
            raise ValueError(f"Invalid ENCRYPTION_KEY: {exc}") from exc

    # ── Public API ────────────────────────────────────────────────────────────

    def encrypt(self, plaintext: Optional[str]) -> Optional[bytes]:
        """Encrypt a string to bytes. Returns None for None/empty input."""
        if not plaintext:
            return None
        try:
            return self._fernet.encrypt(plaintext.encode("utf-8"))
        except Exception as exc:
            logger.error("Encryption failed: %s", exc)
            return None

    def decrypt(self, ciphertext: Optional[bytes]) -> Optional[str]:
        """Decrypt bytes back to a string. Returns None on any failure."""
        if not ciphertext:
            return None
        try:
            return self._fernet.decrypt(ciphertext).decode("utf-8")
        except InvalidToken:
            logger.warning("Decryption failed – invalid token or wrong key")
            return None
        except Exception as exc:
            logger.error("Decryption error: %s", exc)
            return None

    # ── Key management ────────────────────────────────────────────────────────

    @staticmethod
    def generate_key() -> str:
        """Generate a fresh Fernet key (call once, store securely)."""
        return Fernet.generate_key().decode()

    def rotate_key(self, new_key: str, ciphertext: bytes) -> Optional[bytes]:
        """
        Re-encrypt data under a new key (for key rotation workflows).
        Returns the new ciphertext or None on failure.
        """
        try:
            plaintext = self._fernet.decrypt(ciphertext)
            new_fernet = Fernet(new_key.encode())
            return new_fernet.encrypt(plaintext)
        except Exception as exc:
            logger.error("Key rotation failed: %s", exc)
            return None
